version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: bookeeping
      POSTGRES_PASSWORD: bookeeping
      POSTGRES_DB: bookeeping_django
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
    ports:
      - 5438:5432
  redis:
    image: redis:5.0.5-alpine
    expose:
      - 6379
    volumes:
      - ./docker/files/redis:/var/lib/redis
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn bookeeping.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_vol:/code/staticfiles
    env_file: .env
    expose:
      - 8000
    depends_on:
      - db
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - static_vol:/staticfiles
    ports:
      - 80:80
    depends_on:
      - back
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - .\bot:/code/:rw
    command: python bot.py
    depends_on:
      - web

volumes:
  static_vol:
  postgres:
