# Generated by Django 2.2.3 on 2019-07-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190719_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='name',
        ),
    ]
